var abi = /* abi generated by compiler */
var ZombieFeedingContract = web3.eth.contract(abi)
var contractAddress = /* contract addres on Ethereum after dpeloying */
var ZombieFeeding = ZombieFeedingContract.at(contractAddress)

// assuming we have zombie ID and kitty ID we want to attack:
let zombieId = 1;
let kittyId = 1;

// To get the CryptoKitty's image, we need to query their web API. This
// information isn't stored on the blockchain, just their webserver.
// If everything was stored on a blockchain, we wouldn't have to worry
// about the server going down, them changing their API, or the company 
// blocking us from loading their assets if they don't like our zombie game ;)
let apiUrl = "https://api.cryptokitties.co/kitties/" + kittyId
$.get(apiUrl, function (data) {
    let imgUrl = data.image_url
    //do something to display image
})

//when user clicks a kitty:
$(".kittyImage").click(function (e) {
    //call our contract's `feedOnKitty` method
    ZombieFeeding.feedOnKitty(zombieId, kittyId)
})

//listen for NewZombie event from contract, to update front-end:
ZombieFactory.NewZombie(function (error, result) {
    if (error) return
    //this fn will display the zombie:
    generateZombie(result.zombieId, result.name, result.dna)
})